### ISSUE TITLE
segfault while accessing syscatalogue outside a transaction

### ISSUE THREAD

**Issue by nikkhils** [dimitri/pgextwlist#54]
We observed a segfault with the following stack trace:

```
(gdb) bt
#0  0x0000000000549ae3 in GetRealCmin (combocid=0) at utils/time/combocid.c:283
#1  HeapTupleHeaderGetCmin (tup=<optimized out>) at utils/time/combocid.c:112
..snip..
#21 0x000000000095c3c2 in SearchCatCacheMiss (cache=cache@entry=0x179a100, nkeys=nkeys@entry=1, hashValue=hashValue@entry=3829442659, hashIndex=hashIndex@entry=3, v1=v1@entry=18654, v2=v2@entry=0, v3=0, v4=0)
    at utils/cache/catcache.c:1360
#22 0x000000000095c736 in SearchCatCacheInternal (cache=0x179a100, nkeys=1, v1=18654, v2=0, v3=0, v4=0) at utils/cache/catcache.c:1300
#23 0x000000000099d415 in SearchCatCache1 (v1=18654, cache=<optimized out>) at utils/cache/catcache.c:1168
#24 SearchSysCache1 (key1=18654, cacheId=11) at utils/cache/syscache.c:1123
#25 superuser_arg (roleid=18654) at utils/misc/superuser.c:70
#26 0x000000000099d48f in superuser () at utils/init/miscinit.c:450
#27 0x00007fc27d8cae2a in extwlist_ProcessUtility (pstmt=0x16d61a0, queryString=0x16d5688 "ROLLBACK", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x16d5ef8, qc=0x7ffe7369e9c0)
    at /usr/src/debug/postgresql13-pgextwlist-1.12-1.aiven.3.g3b4ec9b.fc35.x86_64/pgextwlist.c:305
#28 0x00007fc27d8708a3 in prev_ProcessUtility () from /usr/pgsql-13/lib/timescaledb-2.8.1.so
```

The issue is coming because the call to the `superuser()` function from `pgextwlist` code above is happening when there's no transaction in progress. Maybe the DDL code can check for a valid transaction before doing any further processing?

**Comment by nikkhils** [comment]
https://github.com/dimitri/pgextwlist/pull/55 related PR
